#!/usr/bin/env python

import requests, optparse, sys, json

def main():
   wbench_json = json.loads(file("/var/www/wbench.json").read())
   usage = "usage: %prog [options]"
   parser = optparse.OptionParser(usage=usage)
   parser.add_option("-s", "--switch", help="Comma separated switch names. eg leaf1,spine1", dest="switches")
   parser.add_option("-a", "--all", action="store_true", help="All switches", dest="all")

   USER = wbench_json["reservation"]["workbench"]["user"]
   APIKEY = wbench_json["reservation"]["workbench"]["api_key"]
   APIURL = wbench_json["reservation"]["workbench"]["api_url"]
   switcharr = wbench_json["reservation"]["workbench"]["switcharr"]


   usage = "usage: %prog [options]"
   parser = optparse.OptionParser(usage=usage)
   parser.add_option("-o", "--operation", help="off,on,reset", dest="operation")
   parser.add_option("-s", "--switch", help="Comma separated switch names. eg leaf1,spine1", dest="switches")
   parser.add_option("-a", "--all", action="store_true", help="All switches", dest="all")

   (options, args) = parser.parse_args()
   operation = options.operation
   switches  = options.switches
   all = options.all

   if not operation:
      print "Please specify an operation"
      sys.exit(1)
   if not operation in ['off', 'on', 'reset']:
      print "%s not a valid operation" % operation
      sys.exit(1)
   if not all and not switches:
      print "Please specify the switches"
      sys.exit(1)
   if all:
      if switches:
         print "-a and -s options cannot be together"
         sys.exit(1)
      else:
         swlist = switcharr.keys()
   
   if switches:
      swlist = filter(len, switches.split(','))
      for sw in swlist:
         if not sw in switcharr.keys():
            print "Unknown switch %s, valid values are %s" % (sw, switcharr.keys())
            sys.exit(0)

   if operation == "reset":
      data = {'pcycle':'1'}
   if operation == "off":
      data = {'pcycle':'2'}
   if operation == "on":
      data = {'pcycle':'3'}
   headers = {'content-type': 'application/json'}
   for sw in swlist:
      url = APIURL+"cw/switch/%s/" % switcharr[sw]
      params = {'username':USER, 'api_key':APIKEY, 'switch':switcharr[sw]}
      r = requests.put(url, params=params, data=json.dumps(data), headers=headers)
      if not r.status_code == 204:
         print "Error %s'ing %s. Status code: %s, Error %s" % (operation, sw, r.status_code, r.content)
      else:
         print "Power %s of switch %s successful" % (operation, sw)

if __name__ == "__main__":
    main()

